# Spring properties
spring:
  application:
    name: JingIM  # Service registers under this name

  redis:
    database: 0
   # Redis服务器地址
    host: 39.107.236.239
   # Redis服务器连接端口
    port: 6379
   # Redis服务器连接密码（默认为空）
    password:
   # 连接超时时间（毫秒）
    timeout: 0
   # 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 10
   # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 10000
   # 连接池中的最大空闲连接
      max-idle: 20
   # 连接池中的最大空闲连接
      min-idle: 5


management:
  security:
    enabled: false