# Spring properties
spring:
  application:
    name: JingIM  # Service registers under this name
  # Datasource
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://39.107.236.239:3306/websocket?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  # Redis Configration
  redis:
    database: 0
   # Redis服务器地址
    host: 39.107.236.239
   # Redis服务器连接端口
    port: 6379
   # Redis服务器连接密码（默认为空）
    password:
   # 连接超时时间（毫秒）
    timeout: 0
   # 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 10
   # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 10000
   # 连接池中的最大空闲连接
      max-idle: 20
   # 连接池中的最大空闲连接
      min-idle: 5

# Mybayis
mybatis:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: ml.jinggo.entity
  type-handlers-package: ml.jinggo.entity
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    default-fetch-size: 100
    default-statement-timeout: 30

management:
  security:
    enabled: false